# Generated by Django 4.2.16 on 2024-11-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='is_recurrent',
            field=models.BooleanField(default=False),
        ),
    ]
